# -*- coding: utf-8 -*-
"""final_project_exploration (cleaned).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v-eicKpGxYMNAfnVMPcm-6oJ-UljLe46

# California Wildfires: Economic Impact Analysis
**Authors:** Colin Trevino-Odell& Paige Murray  
**Course:** DATA 271 — Cal Poly Humboldt  

---

## 1. Introduction

California's wildfire crisis is worsening — in lives lost, structures destroyed, and dollars spent. This project examines the economic impact of wildfires on affected communities by analyzing fire incident data alongside county-level tax revenue. We focus on two case studies:

- **The Camp Fire (November 2018)** — Butte County, the deadliest and most destructive wildfire in California history
- **The Eaton Fire (January 2025)** — Los Angeles County, the second most destructive wildfire in California history

We use county tax revenue as a single metric that captures both the economic wellbeing of residents and the fiscal capacity of local government — when revenue drops, it means the community is generating less economic activity *and* the county has fewer resources to respond and rebuild.

## 2. Libraries

All libraries used in this analysis are loaded below.
"""

import numpy as np           # numerical operations
import pandas as pd          # data manipulation and analysis
import matplotlib.pyplot as plt  # plotting
import seaborn as sns        # statistical visualizations
import os                    # file system navigation
import warnings

sns.set_style('darkgrid')
warnings.filterwarnings('ignore')

"""## 3. Data Preparation

### 3.1 Loading the Data

We mount Google Drive and set the working directory to our project folder, then load all three datasets.
"""

from google.colab import drive
drive.mount('/content/drive')

# Set working directory to our project folder
for root, dirs, files in os.walk('/content/drive/MyDrive/School/271 fire project /'):
    if 'calfire.csv' in files and 'kaggle.csv' in files:
        os.chdir(root)
        print(f'Working directory set to: {root}')
        break

# Load all three datasets
calfire = pd.read_csv('calfire.csv')
kaggle = pd.read_csv('kaggle.csv')
countrevs = pd.read_csv('county_revenues.csv')

"""### 3.2 Dataset 1: CAL FIRE Historical Fire Perimeters

**Source:** [California Natural Resources Agency](https://data.cnra.ca.gov/dataset/california-fire-perimeters-all)  
**Original purpose:** CAL FIRE maintains this dataset to track the geographic boundaries (perimeters) of all wildfires in California. It is used for fire management, land use planning, and historical analysis.  
**Time span:** 1878–2025  
**Variables:** 22 columns covering fire identification, geography, cause classification, and perimeter geometry.  

**Peculiarities:**
- The `Year` column is stored as a float (contains NaN values for some older records)
- `Alarm Date` and `Containment Date` are strings, not datetime objects
- The `Cause` column uses integer codes rather than descriptive labels
- Many older records (pre-1950) have significant missing data across multiple columns
"""

print('Shape:', calfire.shape)
print()
calfire.info()

calfire.head()

calfire.describe()

"""### 3.3 Dataset 2: California Wildfire Incidents (Kaggle)

**Source:** [Kaggle — California Wildfire Incidents](https://www.kaggle.com/datasets/ananthu017/california-wildfire-incidents-20132020)  
**Original purpose:** This dataset was compiled to provide detailed incident-level information about California wildfires, including human impact (fatalities, injuries), resource deployment (engines, helicopters, personnel), and structural damage.  
**Time span:** Primarily 2013–2019  
**Variables:** 40 columns covering fire details, resource allocation, and human/structural impact.  

**Peculiarities:**
- The `Started` column has inconsistent date formatting — use string slicing (`str[:4]`) for year extraction rather than datetime parsing
- Many resource columns (AirTankers, Dozers, CrewsInvolved, etc.) have significant NaN values
- `StructuresEvacuated` and `StructuresThreatened` are sparsely populated
"""

print('Shape:', kaggle.shape)
print()
kaggle.info()

kaggle.head()

kaggle.describe()

"""### 3.4 Dataset 3: County Revenues Per Capita

**Source:** [California State Controller's Office](https://data.ca.gov/dataset/county-revenues-per-capita)  
**Original purpose:** The State Controller's Office publishes this data as part of California's government transparency initiative. It reports total revenues collected by each of California's 58 counties, along with estimated population and per capita revenue figures.  
**Time span:** Fiscal years 2003–2024 (Eaton fire not included)

**Variables:** 5 columns — Entity Name, Fiscal Year, Total Revenues, Estimated Population, Revenues Per Capita.  

**Peculiarities:**
- Humboldt County shows $0 revenue for FY 2020 and 2021 (likely a reporting gap, not actual zero revenue)
- Revenue figures include all county revenue sources (property tax, sales tax, intergovernmental transfers, fees, and disaster relief funds)
- Post-disaster revenue spikes may reflect FEMA and state emergency funding rather than organic economic activity
"""

print('Shape:', countrevs.shape)
print()
countrevs.info()

countrevs.head()

countrevs.describe()

"""## 4. Exploratory Data Analysis

*Analysis to follow — focusing on Camp Fire (Butte County) and Eaton Fire (Los Angeles County) economic impact through county revenue trends.*
"""



"""## 5. Summary

*To be completed.*
"""